sudo: required

language: java

services:
  - docker

env:
  - JAVAVER="oracle17"
  - JAVAVER="oracle18"
  - JAVAVER="openjdk17"
  - JAVAVER="openjdk18"
  - JAVAVER="openjdk17-devel"
  - JAVAVER="openjdk18-devel"
  - JAVAVER="oracle19"

before_install:
  - sudo apt-get update
  - sudo DEBIAN_FRONTEND=noninteractive apt-get -y -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confnew" install docker-engine
  - docker -v

install:
  - make BUILDARGS="--build-arg JAVAVER=$JAVAVER --build-arg USER_ID=$UID"

script:
  - ./runtest.sh
