---
name: Build

on: 
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  build:
    strategy:
      matrix:
        java:
          - 'openjdk1.8'
          - 'openjdk1.8-devel'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: make BUILDARGS="--build-arg JAVAVER=${{ matrix.java }} --build-arg USER_ID=$UID"
      - name: Test
        run: ./runtest.sh
